# docker-compose.yml
services:
  ################################
  # API GATEWAY / REVERSE PROXY
  ################################
  gateway:
    image: traefik:v2.11
    container_name: traefik_gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # For Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./gateway/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./gateway/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./gateway/certs:/etc/traefik/certs:ro # Mount certificates
    networks:
      - localai_net
    labels:
      - "traefik.enable=true"
      # This makes the dashboard available at http://${DOMAIN_NAME}:8080/dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=traefik"

  ################################
  # FRONTEND SERVICE (SvelteKit + Nginx)
  ################################
  frontend:
    build:
      context: ./frontend
    container_name: frontend_ui
    restart: unless-stopped
    networks:
      - localai_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend-svc.loadbalancer.server.port=80"

  ################################
  # CORE SERVICE (Sessions, Settings, DB)
  ################################
  core-service:
    build:
      context: ./services/core-services
    container_name: core_service
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - localai_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core-service.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api/sessions`, `/api/settings`, `/api/icons`)"
      - "traefik.http.routers.core-service.priority=5"
      - "traefik.http.routers.core-service.entrypoints=https"
      - "traefik.http.routers.core-service.tls=true"
      - "traefik.http.services.core-svc.loadbalancer.server.port=8000"

  ################################
  # CHAT SERVICE (LLM Interaction)
  ################################
  chat-service:
    build:
      context: ./services/chat-services
    container_name: chat_service
    restart: unless-stopped
    networks:
      - localai_net
    environment:
      - CORE_SERVICE_URL=http://core-service:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-service.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api/chat`)"
      - "traefik.http.routers.chat-service.priority=5"
      - "traefik.http.routers.chat-service.entrypoints=https"
      - "traefik.http.routers.chat-service.tls=true"
      - "traefik.http.services.chat-svc.loadbalancer.server.port=8000"

  ################################
  # TTS SERVICE
  ################################
  tts-service:
    build:
      context: ./services/tts-service
    container_name: tts_service
    restart: unless-stopped
    networks:
      - localai_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tts-service.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/api/tts`)"
      - "traefik.http.routers.tts-service.priority=10"
      - "traefik.http.routers.tts-service.entrypoints=https"
      - "traefik.http.routers.tts-service.tls=true"
      - "traefik.http.services.tts-svc.loadbalancer.server.port=5001"
  qdrant-db:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant_db
    restart: unless-stopped
    ports:
      - "6333:6333" # Main REST API port
      - "6334:6334" # gRPC port
    volumes:
      - ./data/qdrant_storage:/qdrant/storage:rw
      - ./configuration/qdrant/config.yaml:/qdrant/config/production.yaml
    networks:
      - localai_net
networks:
  localai_net:
    driver: bridge