services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  tts:
    build: ./tts_service
    ports:
      - "5001:5001"
    restart: unless-stopped