# gateway/traefik.yml
# Define the network entry points (ports)
entryPoints:
  http:
    address: ":80"
    # Global redirect from http to https
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  traefik:
    address: ":8080" # Traefik dashboard entrypoint

# Enable the API and dashboard
api:
  dashboard: true # Enable the dashboard UI
  insecure: true  # Allow access over HTTP on the dedicated 'traefik' entrypoint

# Tell Traefik where to find routing configurations
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: localai_net # Use the specific network
  file:
    filename: /etc/traefik/dynamic.yml # Point to the dynamic config file for TLS
    watch: true

log:
  level: INFO